model_fix:
  prot_in_dim: 1280   
  prot_hidden_dim: 512
  node_dim: 52 
  edge_dim: 10
  num_layer: 2
  prot_mol_dim: 256

model_opt:
  inter_heads: 8
  num_cluster: 10

num_workers_train: 4
prefetch_factor: 4

weight_pocket: 0.5

pretrain_model_path: xxxxx/ckpt/xxx/checkpoints/model_valid.pth